language: cpp

compiler: gcc

before_install:
    - sudo add-apt-repository -y ppa:vslavik/poedit
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq --no-install-recommends asciidoc xsltproc xmlto
    - sudo apt-get install -qq libexpat1-dev libdb++-dev libboost-dev libboost-regex-dev libboost-system-dev liblucene++-dev libicu-dev libwxgtk3.0-dev libgtk2.0-dev libgtkspell-dev

script:
    - $CXX --version
    - scripts/travis-check-translations.sh
    # don't build directly, create a tarball first and try building from that
    - ./bootstrap && ./configure && make dist && make distcheck

git:
    submodules: false

cache: apt
